spring:
  application:
    name: crm-auth-service
  config:
    import: "optional:configserver:http://localhost:8888"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}


  datasource:
    url: jdbc:h2:mem:localdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver


  flyway:
    enabled: false
